CREATE TABLE IF NOT EXISTS test.NOTEBOOK
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(16) NOT NULL,
    LAST_NAME VARCHAR(16) NOT NULL,
    AGE TINYINT,
    GENDER CHAR(1),
    PHONE_NUMBER VARCHAR(13) UNIQUE
);

use test;

ALTER TABLE `NOTEBOOK` ADD UNIQUE `person_index`(`FIRST_NAME`, `LAST_NAME`);